<template>
    <div>
        <p>
            A gene co-expression network (GCN) is an undirected graph, where each node corresponds to a gene, and a pair of nodes is connected with an edge if there is a significant co-expression relationship between them.[1] Having gene expression profiles of a number of genes for several samples or experimental conditions, a gene co-expression network can be constructed by looking for pairs of genes which show a similar expression pattern across samples, since the transcript levels of two co-expressed genes rise and fall together across samples. Gene co-expression networks are of biological interest since co-expressed genes are controlled by the same transcriptional regulatory program, functionally related, or members of the same pathway or protein complex.[2]

The direction and type of co-expression relationships are not determined in gene co-expression networks; whereas in a gene regulatory network (GRN) a directed edge connects two genes, representing a biochemical process such as a reaction, transformation, interaction, activation or inhibition.[3] Compared to a GRN, a GCN does not attempt to infer the causality relationships between genes and in a GCN the edges represent only a correlation or dependency relationship among genes.[4] Modules or the highly connected subgraphs in gene co-expression networks correspond to clusters of genes that have a similar function or involve in a common biological process which causes many interactions among themselves.[3]


The direction of edges is overlooked in gene co-expression networks. While three genes X, Y and Z are found to be co-expressed, it is not determined whether X activates Y and Y activates Z, or Y activates X and Z, or another gene activates three of them.
Gene co-expression networks are usually constructed using datasets generated by high-throughput gene expression profiling technologies such as Microarray or RNA-Seq.
        </p>
        <hr>
        <div id="co-expression-graph" style="width: 1000px;height:600px;"></div>
    </div>
</template>
<script>
    import * as echarts from "echarts";
    import axios from "axios";
    export default{
        data:function(){
            return {
                
            }
        },
        methods:{
        },
        mounted:function(){
            var myChart = echarts.init(document.getElementById("co-expression-graph"));
            var option = {
                title:{
                    text:"statics of links and nodes"
                },
                tooltip:{
                    trigger:'axis',
                    axisPointer:{
                        type:'shadow'
                    }
                },
                toolbox:{
                    feature:{
                        dataView:{
                            show:true,
                            readOnly:false
                        },
                        magicType:{
                            show:true
                        },
                        restore:{
                            show:true
                        },
                        saveAsImage:{
                            show:true
                        }
                    }
                },
                legend:{
                    data:["links number","nodes number"]
                },
                xAxis:[
                    {
                        type:"category",
                        data:['s1','s2','s3','s4','s5','s6','s7']
                    }
                ],
                yAxis:[
                    {
                        type:"value",
                        name:"links number",
                        min:0,
                        max:80,
                        axisLabel:{
                            formatter:'{value}'
                        }
                    },
                    {
                        type:"value",
                        name:"nodes number",
                        min:0,
                        max:180,
                        axisLabel:{
                            formatter:'{value}'
                        }
                    },
                ],
                series:[
                    {
                        name:"links number",
                        type:"bar",
                        data:[20,30,23,15,77,53]
                    },
                    {
                        name:"transcript number",
                        type:"bar",
                        yAxisIndex:1,
                        data:[66,88,176,53,100,40]
                    }
                ]
            };
            myChart.setOption(option);
            myChart.on('click',function(params){
                console.log(params.name);
                location.assign('/co_expression/sorghum_bicolor');
            })
        }
    }
</script>
<style>

</style>